image: pikalab/ci:arch-jre14-node14

Test:
  stage: test
  script: 
    - npm install
    - npm run compile-grammar
    - npm run transpile-grammar
    - npm test

Release:
  stage: deploy
  script: 
    - npm install
    - npm run compile-grammar
    - npm run transpile-grammar
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm publish --tag beta
  only:
    - /^(master)|(release)$/

